services:
  app:
    image: taskforce
    ports:
      - 8000:5000
    environment:
      POSTGRES_HOST: psql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mytest
      
  psql:
    image: postgres
    ports:
      - 5445:5432
    volumes:
      - todo-mysql-data:/var/lib/psql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mytest

volumes:
  todo-mysql-data: